### ISSUE TITLE
java.lang.NullPointerException         at dev.alejandrorosas.streamlib.StreamService.stopStream(StreamService.kt:105)

### ISSUE THREAD

**Issue by Allan-Nava** [alejandrorosas/android-uvc-rtmp-stream#83]
```

2021-12-10 10:01:33.115 13574-13616/dev.alejandrorosas.apptemplate D/UsbDeviceConnectionJNI: close
2021-12-10 10:01:33.117 13574-13616/dev.alejandrorosas.apptemplate E/AndroidRuntime: FATAL EXCEPTION: USBMonitor
    Process: dev.alejandrorosas.apptemplate, PID: 13574
    java.lang.NullPointerException
        at dev.alejandrorosas.streamlib.StreamService.stopStream(StreamService.kt:105)
        at dev.alejandrorosas.streamlib.StreamService$onDeviceConnectListener$1.onDisconnect(StreamService.kt:195)
        at com.serenegiant.usb.USBMonitor$UsbControlBlock.close(USBMonitor.java:1357)
        at com.serenegiant.usb.UVCCamera.close(UVCCamera.java:243)
        at com.serenegiant.usb.UVCCamera.destroy(UVCCamera.java:434)
        at dev.alejandrorosas.streamlib.StreamService$onDeviceConnectListener$1.onConnect(StreamService.kt:181)
        at com.serenegiant.usb.USBMonitor$4.run(USBMonitor.java:600)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by alejandrorosas** [comment]
this https://github.com/alejandrorosas/android-uvc-rtmp-stream/pull/84 should fix the NPE

**Comment by Allan-Nava** [comment]
thanks
